version: "3.7"
services:

  front:
    image: aris8/app-front:v1
    ports:
      - "3001:3001"
    networks:
      - myapp

  back:
    image: aris8/app-back:v1
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    image: aris8/app-data:v1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp
  
  datascript:
    image: aris8/app-data-script:v1
    depends_on:
      - data
    environment:
      MYSQL_HOST: "data"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "mydatabase"
    networks:
      - myapp
 
networks:
  myapp:
    driver: bridge
